function listcarier=Carier(num)
if num==1
    listcarier = {'where' 'look' 'can' 'do' 'where' 'look' 'where' 'look'...
        'where' 'can' 'do' 'where' 'look' 'do' 'do' 'where' 'can' 'where'...
        'can' 'can' 'where'  'where' 'can' 'where' 'do' 'look' 'where' 'do'...
        'where' 'can' 'can' 'do' };
elseif num==2
    listcarier= {'where' 'where' 'do' 'can' 'where' 'where' 'can' 'can' ...
        'look' 'where' 'where' 'look' 'do' 'can' 'look' 'can' 'do' 'do'...
        'can' 'do' 'where' 'where' 'where' 'look' 'where' 'where' 'do' 'can'...
        'can' 'where' 'do' 'do'};
elseif num==3
    listcarier= {'here' 'that' 'think' 'think' 'here' 'is' 'here' 'here' ...
        'that' 'is' 'that' 'that' 'think' 'that' 'is' 'is' 'here' 'think'...
        'is' 'that' 'think' 'here' 'think' 'here' 'that' 'think' 'here' ...
        'think' 'here' 'think' 'that' 'think'};
elseif num==4
    listcarier= {'that' 'here' 'that' 'here' 'is' 'here' 'is' 'is' 'think'...
        'here' 'that' 'think' 'that' 'that' ' think' 'here' 'think' 'here'...
        'here' 'think' 'here' 'here' 'think' 'think' 'is' 'is' 'that' 'think'...
        'think' 'here' 'is' 'that'};

end
