function listImage=Image(num)
if num==1
     listImage=[{'Mouth3' ; 'Apple1'} {'Hair1'; 'Banana1'} ...
        {'Hand1';'Yogurt2'} {'Cookie1';'Eyes1'} {'Bottle3';'Leg1'} ...
        {'Eyes2';'Cookie3'} {'Nose2';'Juice1'} {'Banana2';'Hair3'} ...
        {'Apple1';'Mouth3'} {'Spoon3';'Ear1'} {'Milk1';'Foot3'} ...
        {'Mouth1';'Apple3'} {'Hair3';'Banana2'}...
        {'Foot2';'Milk2'} {'Cookie3';'Eyes2'} {'Bottle1';'Leg3'}...
        {'Ear1';'Spoon3'} {'Juice1';'Nose2'} {'Ear3';'Spoon1'} ...
        {'Hand2';'Yogurt3'} {'Leg3';'Bottle1'} ...
        {'Apple3';'Mouth1'} {'Yogurt3';'Hand2'} {'Juice3';'Nose1'} ...
        {'Foot3';'Milk1'} {'Banana1';'Hair1'} {'Nose1';'Juice3'} ...
        {'Milk2';'Foot2'} {'Leg1';'Bottle3'} {'Spoon1';'Ear3'} ...
        {'Yogurt2';'Hand1'} {'Eyes1';'Cookie1'}];
elseif num==2
    listImage=[{'Mouth1';'Apple3'} {'Juice1';'Nose2'} {'Eyes2';'Cookie3'} ...
        {'Ear1';'Spoon3'}  {'Apple1';'Mouth3'} ...
        {'Leg1';'Bottle3'} {'Hand1';'Yogurt2'} {'Spoon1';'Ear3'} {'Banana1';'Hair1'} ...
        {'Nose2';'Juice1'} {'Mouth3';'Apple1'} ...
        {'Hair1';'Banana1'} {'Milk2';'Foot2'} ...
        {'Yogurt3';'Hand2'} {'Hair3';'Banana2'} {'Spoon3';'Ear1'} ...
        {'Foot2';'Milk2'} {'Eyes1';'Cookie1'} ...
        {'Hand2';'Yogurt3'} {'Cookie1';'Eyes1'} {'Bottle1';'Leg3'} ...
        {'Apple3';'Mouth1'} {'Nose1';'Juice3'} ...
        {'Banana2';'Hair3'} {'Bottle3';'Leg1'} {'Juice3';'Nose1'}...
        {'Foot3';'Milk1'} {'Yogurt2';'Hand1'} {'Ear3';'Spoon1'}...
        {'Leg3';'Bottle1'} {'Milk1';'Foot3'} {'Cookie3';'Eyes2'}];
    
elseif num==3
    listImage= {'Eyes_Match-Mismatch' 'Banana_Match-Mismatch' 'Mouth_Match-Mismatch'...
        'Bottle_Match-Mismatch' 'Banana_Match-Mismatch' 'Eyes_Match-Mismatch' ...
        'Eyes_Match-Mismatch' 'Bottle_Match-Mismatch' 'Banana_Match-Mismatch'...
        'Eyes_Match-Mismatch' 'Bottle_Match-Mismatch' 'Mouth_Match-Mismatch'...
        'Bottle_Match-Mismatch' 'Mouth_Match-Mismatch' 'Bottle_Match-Mismatch'...
        'Banana_Match-Mismatch' 'Eyes_Match-Mismatch' 'Bottle_Match-Mismatch'...
        'Mouth_Match-Mismatch' 'Banana_Match-Mismatch' 'Banana_Match-Mismatch'...
        'Eyes_Match-Mismatch' 'Mouth_Match-Mismatch' 'Banana_Match-Mismatch'...
        'Bottle_Match-Mismatch' 'Eyes_Match-Mismatch' 'Mouth_Match-Mismatch'...
        'Bottle_Match-Mismatch' 'Mouth_Match-Mismatch' 'Banana_Match-Mismatch'...
        'Eyes_Match-Mismatch' 'Mouth_Match-Mismatch'};

elseif num==4
    listImage= {'Eyes_Match-Mismatch' 'Mouth_Match-Mismatch' 'Banana_Match-Mismatch'...
        'Bottle_Match-Mismatch' 'Eyes_Match-Mismatch' 'Bottle_Match-Mismatch'...
        'Mouth_Match-Mismatch' 'Bottle_Match-Mismatch' 'Banana_Match-Mismatch'...
        'Eyes_Match-Mismatch' 'Mouth_Match-Mismatch' 'Mouth_Match-Mismatch'...
        'Eyes_Match-Mismatch' 'Banana_Match-Mismatch' 'Eyes_Match-Mismatch'...
        'Mouth_Match-Mismatch' 'Banana_Match-Mismatch' 'Bottle_Match-Mismatch'...
        'Banana_Match-Mismatch' 'Mouth_Match-Mismatch' 'Eyes_Match-Mismatch'...
        'Banana_Match-Mismatch' 'Bottle_Match-Mismatch' 'Bottle_Match-Mismatch'...
        'Eyes_Match-Mismatch' 'Banana_Match-Mismatch' 'Bottle_Match-Mismatch'...
        'Banana_Match-Mismatch' 'Eyes_Match-Mismatch' 'Mouth_Match-Mismatch'...
        'Bottle_Match-Mismatch' 'Mouth_Match-Mismatch'};
end

