function listlabel=Label(num)
if num==1
   listlabel = {'apple' 'hair' 'hand' 'cookie' 'leg' ...
        'cookie' 'juice' 'hair' 'mouth' 'spoon' 'milk' ...
        'mouth' 'banana' 'milk' 'eyes' 'bottle' 'ear' ...
        'nose' 'spoon' 'yogurt' 'leg' 'apple' 'hand' ...
        'juice' 'foot' 'banana' 'nose' 'foot' 'bottle' 'ear' ...
        'yogurt' 'eyes'};
elseif num==2
    listlabel= {'apple' 'juice' 'eyes' 'spoon' 'apple' ...
        'leg' 'yogurt' 'spoon' 'hair' 'nose' 'mouth' 'banana' ...
        'milk' 'yogurt' 'hair' 'ear' 'foot' ...
        'cookie' 'hand' 'eyes' 'leg' 'mouth' 'juice' ...
        'banana' 'bottle' 'nose' 'milk' 'hand' 'ear'...
        'bottle' 'foot' 'cookie'};
elseif num==3
    listlabel= {'eyes' 'mouth' 'banana' 'bottle' 'mouth' 'eyes' 'bottle'...
        'eyes' 'banana' 'bottle' 'bottle' 'mouth' 'eyes' 'banana' 'bottle'...
        'mouth' 'bottle' 'bottle' 'banana' 'mouth' 'banana' 'eyes' 'mouth'...
        'banana' 'eyes' 'eyes' 'mouth' 'eyes' 'banana' 'banana' 'bottle' ...
        'mouth'};
elseif num==4
    listlabel= {'eyes' 'eyes' 'banana' 'banana' 'mouth' 'bottle' 'eyes' ...
        'banana' 'banana' 'mouth' 'mouth' 'mouth' 'mouth' 'bottle' 'eyes'...
        'mouth' 'bottle' 'banana' 'banana' 'eyes' 'eyes' 'bottle' 'bottle'...
        'banana' 'eyes' 'banana' 'bottle' 'bottle' 'mouth' 'mouth' 'bottle'...
        'eyes'};

end
