function listTrialT=TrailType(num)
if num==1
    listTrialT = {'dt' 'td' 'td' 'td' 'dt' 'dt' 'dt' 'dt' 'dt' 'td' 'td' ...
        'td' 'dt' 'dt' 'dt' 'td' 'td' 'dt' 'dt' 'dt' 'td' 'td' 'dt' 'td'...
        'td' 'td' 'td' 'dt' 'dt' 'dt' 'td' 'td'};
elseif num==2
    listTrialT= {'dt' 'td' 'td' 'dt' 'td' 'td' 'dt' 'td' 'dt' 'td' 'td' 'dt' ...
        'td' 'td' 'td' 'dt' 'td' 'dt' 'td' 'dt' 'dt' 'dt' 'dt' 'td' 'td' 'dt' ...
        'dt' 'dt' 'td' 'dt' 'dt' 'td'};
elseif num==3
    listTrialT = {'Match' 'MMInter' 'MMInter' 'Match' 'MMInter' 'Match'...
        'MMInter' 'MMInter' 'Match' 'MMInter' 'Match' 'Match' 'MMInter'...
        'MMInter' 'Match' 'MMInter' 'MMInter' 'Match' 'MMInter' 'MMInter' ...
        'Match' 'Match' 'Match' 'Match' 'MMInter' 'Match' 'Match' 'MMInter'...
        'MMInter' 'Match' 'MMInter' 'Match'};
elseif num==4
    listTrialT= {'Match' 'Mmintra' 'Match' 'Mmintra' 'Mmintra' 'Match' 'Mmintra'...
        'Mmintra' 'Match' 'Mmintra' 'Match' 'Match' 'Mmintra' 'Mmintra' 'Match'...
        'Match' 'Mmintra' 'Mmintra' 'Match' 'Mmintra' 'Match' 'Mmintra' ...
        'Match' 'Mmintra' 'Match' 'Match' 'Match' 'Mmintra' 'Mmintra' 'Match'...
        'Match' 'Mmintra'};

end
